# configure-tomcat.yml
# here we do all the configuration related to Tomcat

# In development we copy sample.war to the the remote server
# This helps troubleshooting when developers upload a new java
# application and all hell breaks !

# Only transfer sample.war if initial testing with TomCat required.

---
#- name: Transfer sample.war
#  copy:
#    src: "sample.war"
#    dest: "{{ tomcat_dir }}/latest/webapps"


- name: Transfer tomcat server.xml
  template:
    src: "tomcat_server.xml.j2"
    dest: "{{ tomcat_dir }}/latest/conf/server.xml"
    mode: 0600
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Transfer setenv.sh
  template:
    src: "setenv.sh"
    dest: "{{ tomcat_dir }}/latest/bin/setenv.sh"
    mode: 0764
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Recursively change ownership of tomcat log directory. This allows developers to monitor log files
  file:
    path: /opt/tomcat/latest/logs
    state: directory
    recurse: yes
    mode: '0755'

- name: Create directory to upload ETL files
  file:
    path: /var/tmp/ETL
    state: directory
    mode: '0775'
    owner: tomcat
    group: tomcat
 
- name: Setup systemd
  template:
    src: "tomcat.service.xml.j2"
    dest: "/etc/systemd/system/tomcat.service"
#  notify: start tomcat

- name: Make sure tomcat is running
  systemd:
    enabled: yes
    state: started
    name: tomcat

