# copy both Oracle java and Tomcat to remote host
---

# Create temp work directory for java
- name: Create temp work directory {{ java_tmp_work_dir }}
  file:
    path: "{{ java_tmp_work_dir }}"
    state: directory
    mode: '0777'


# Copy Java bundle
- name: Copy Java 
  copy:
    src: /home/ec2-user/Work/TomCat/jdk-8u211-linux-x64.tar.gz
    dest: "{{ java_tmp_work_dir }}"
    owner: ec2-user
    group: ec2-user
    mode: 0644
    #force: no       # Remember to remove this when Live



# Create temp work directory for tomcat
- name: Create temp work directory {{ tomcat_tmp_work_dir }}
  file:
    path: "{{ tomcat_tmp_work_dir }}"
    state: directory
    mode: '0777'

# Copy tomcat bundle
- name: example copying file with owner and permissions
  copy:
    src: /home/ec2-user/Work/TomCat/apache-tomcat-9.0.21.tar.gz
    dest: "{{ tomcat_tmp_work_dir }}"
    owner: ec2-user
    group: ec2-user
    mode: 0644
    #force: no       # Remember to remove this when Live

