# install-java.yml
---

- name: Create java group {{ java_group }}
  group:
    name: "{{ java_group }}"
    gid: "{{ tomcat_group_gid | default(omit) }}"
    state: present

- name: Create java user {{ java_user }}
  user:
    name: "{{ java_user }}"
    group: "{{ java_group }}"
    uid: "{{ java_dir_user_uid | default(omit) }}"
    state: present

- name: Create java directory {{ java_dir }}
  file:
    path: "{{ java_dir }}"
    state: directory
    owner: "{{ java_user }}"
    group: "{{ java_group }}"



- name: Unarchive {{ java_tmp_work_dir }}/jdk-{{ tomcat_java_version }}-linux-x64.tar.gz
  unarchive:
    src: "{{ java_tmp_work_dir }}/jdk-{{ tomcat_java_version }}-linux-x64.tar.gz"
    dest: "{{ java_dir }}"
    remote_src: True
    owner: "{{ java_user }}"
    group: "{{ java_group }}"
    creates: "{{ java_dir }}/{{tomcat_jdk_version}}_{{ tomcat_jdk_minor_version }}"
  register: java_installed

#
- name: Set the latest link accordingly for {{ java_dir }}/jdk{{ tomcat_jdk_version }}_{{ tomcat_jdk_minor_version }}
  file:
    src: "{{ java_dir }}/jdk{{ tomcat_jdk_version }}_{{ tomcat_jdk_minor_version}}"
    dest: "{{ java_dir }}/latest"
    state: link
    owner: "{{ java_user }}"
    group: "{{ java_group }}"
